title: "SIGN"
description: "Короткие истории.."
lang: ru
timezone: Europe/Moscow

# вместо theme: minima
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

minimal_mistakes_skin: "dark"   # можно "air", "contrast", "dark" и т.п.

paginate: 10
paginate_path: /page:num/

collections:
  stories:
    output: true